#!/bin/bash
# set -e
# Don't know why this is necessary!
export MAVEN_OPTS=/home/elexis/.m2
build_root=/home/elexis
mkdir -p $build_root
cd $build_root
if [ -d "$build_root/elexis-3-core" ]
then
  echo "Don't clone elexis-3-core"
else
  git clone https://github.com/elexis/elexis-3-core
fi
cd elexis-3-core
mvn clean install -Dmaven.test.skip=true
cd $build_root
if [ -d "$build_root/elexis-3-base" ]
then
  echo "Don't clone elexis-3-base"
else
  git clone https://github.com/elexis/elexis-3-base
fi
cd elexis-3-base
mvn clean install -Dmaven.test.skip=true

