#!/bin/bash -v
# Stop on error
set -e
# Don't know why this is necessary!
mkdir -p $HOME/.m2
build_root=/home/elexis
cd $build_root
if [ -d "$build_root/elexis-3-core" ]
then
  echo "Don't clone elexis-3-core"
else
  git clone https://github.com/elexis/elexis-3-core
fi
cd elexis-3-core
# Add -Dmaven.test.skip=true if you have problems running the tests, eg. no X display
mvn clean install
cd $build_root
if [ -d "$build_root/elexis-3-base" ]
then
  echo "Don't clone elexis-3-base"
else
  git clone https://github.com/elexis/elexis-3-base
fi
cd elexis-3-base
# Add -Dmaven.test.skip=true if you have problems running the tests, eg. no X display
# Currently ch.elexis.base.ch.arzttarife.test is broken
mvn clean install -Dmaven.test.skip=true

