#!/bin/bash -v
containerId=ngiger/elexis
xhost -
host_ip=`docker inspect --format="{{ .Config.Hostname }}" $containerId`
xhost +local:$host_ip
export docker_data=/opt/docker-data-containers/elexis-3.1
echo Will run elexis. Dockerdata lives at $docker_data container $containerId ip is $host_ip
mkdir -p $docker_data/elexis/logs
mkdir -p $docker_data/.eclipse
docker run -ti --rm \
           -e DISPLAY="$DISPLAY" \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v $docker_data:/home/elexis \
           -u elexis $containerId

