#!/bin/bash -v
# stop on any error
set -e
containerId=$USER/elexis_test
xhost -
host_ip=`docker inspect --format="{{ .Config.Hostname }}" $containerId`
xhost +local:$host_ip
export docker_data=$HOME/elexis_test
mkdir -p $docker_data/elexis/logs
mkdir -p $docker_data/.eclipse
echo Will run elexis. Dockerdata lives at $docker_data container $containerId ip is $host_ip
docker run -ti --rm \
           -e DISPLAY="$DISPLAY" \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v $docker_data:/home/elexis \
           --user=elexis \
           $containerId \
           /usr/local/bin/elexis-3

# replace the last line by /bin/bash to run your scripts/app inside the container
