#!/bin/bash -v
set -e
containerId=$USER/build_elexis
export docker_data=$HOME/build_elexis
mkdir -p $docker_data
# For MacOSX: uncomment the next line and adapt it to your host's IP adress
# export DISPLAY=172.25.1.71:0
xhost -
host_ip=`docker inspect --format="{{ .Config.Hostname }}" $containerId`
xhost +local:$host_ip
echo Will build elexis. Dockerdata lives at $docker_data container $containerId ip is $host_ip using display $DISPLAY
docker run -ti --rm \
           -e DISPLAY="$DISPLAY" \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v $docker_data:/home/elexis \
           $containerId \
           /usr/local/bin/build_inside_container

# replace the last line by /bin/bash to run your scripts/app inside the container



